rubric = {
    794901: {
        "name": "Christmas Tree Doubled Variant (T)",
        "q_id": 794901,
        "rubric_description": "",
        "tests": {"q1_io": 3},
        "total_points": 3,
    },
    794904: {
        "name": "Christmas Tree Single Variant (LL)",
        "q_id": 794904,
        "rubric_description": "",
        "tests": {"q1_io": 3},
        "total_points": 3,
    },
    794902: {
        "name": "B-smooth numbers, addition variant",
        "q_id": 794902,
        "rubric_description": "",
        "tests": {"q2_io": 3},
        "total_points": 3,
    },
    794907: {
        "name": "B-smooth numbers, multiplication variant",
        "q_id": 794907,
        "rubric_description": "",
        "tests": {"q2_io": 3},
        "total_points": 3,
    },
    788765: {
        "name": "Bby Got Back",
        "q_id": 788765,
        "rubric_description": "",
        "tests": {"q3_io": 3},
        "total_points": 3,
    },
    794908: {
        "name": "True/False 1",
        "q_id": 794908,
        "rubric_description": "",
        "tests": {"": 1},
        "total_points": 1,
    },
    794903: {
        "name": "True/False 2",
        "q_id": 794903,
        "rubric_description": "",
        "tests": {"": 1},
        "total_points": 1,
    },
    790758: {
        "name": "How are you feeling",
        "q_id": 790758,
        "rubric_description": "",
        "tests": {"": 0},
        "total_points": 0,
    },
}
